name: CHB
favicon: null
layout_spectrum: 0.3843298589345068
typography_spectrum: 0.4694798430427909
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5986824561841786
  lightness: 0.30411080713383853
  saturation: 0.2259284269530326
  rhythmicContrast: 0.45067893131636083
purpose: []
